name: RSS

on:
  schedule:
    - cron: "* * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run script
        run: python rss_to_telegram.py